[package]
name = "gg"
version = "0.1.0"
authors = ["oguzhan.yilmaz <oguzhan.yilmaz@masomo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
